import os
os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"

import torch
from transformers import AutoTokenizer

from utils import print_max_memory
from llm import NemotronHForCausalLM

# MODEL_NAME = "nvidia/NVIDIA-Nemotron-Nano-9B-v2"
MODEL_NAME = "nvidia/Nemotron-H-8B-Base-8K"

MAX_TRAIN_TOKENS = 50


def hook(w):
    w.grad = None
    return


def setup_hooks(model):
    for n, p in model.named_parameters():
        p.register_post_accumulate_grad_hook(hook)


def calculate_loss(model: NemotronHForCausalLM, text, tokenizer, device, max_tokens=MAX_TRAIN_TOKENS):
    tokenizer_kwargs = {"return_tensors": "pt"}
    if max_tokens is not None:
        tokenizer_kwargs.update(
            {
                "max_length": max_tokens,
                "truncation": True,
            }
        )

    inputs = tokenizer(text, **tokenizer_kwargs).to(device)
    print(f"{max_tokens = }")
    print(f'{inputs["input_ids"].shape = }')
    # For causal LM training, labels are usually the same token IDs as inputs.
    # The model shifts them internally when computing next-token loss.
    labels = inputs["input_ids"].clone()

    outputs = model(**inputs, labels=labels, use_cache=False)
    return outputs.loss


def main():
    prompt = """When Korea’s Kospi index plunged 10% last week and triggered a tech stock rout that quickly spread across the world, the country’s new-found status as a powerhouse in global markets was evident.

In large part, this is a manifestation of the crucial role South Korean chipmakers SK Hynix Inc. and Samsung Electronics Co. have come to play in the AI boom that’s powered markets higher. But the bout of frantic selling that day, which sank the Nasdaq 3%, also spotlighted something else: the emergence of a leveraged exchange-traded fund tied to SK Hynix that has grown so large, so fast, analysts say, that it is magnifying swings in both the stock and the entire Kospi index.

In the nine months since the CSOP SK Hynix leveraged ETF was launched in Hong Kong, it has ballooned into a $13 billion fund, the biggest of its kind anywhere, as the chipmaker helped power the Kospi to a nearly 100% gain this year. On volatile days, the ETF and its smaller peers can account for two-thirds of trading in SK Hynix shares — a staggering figure for a company with a $1.2 trillion market value — forcing banks from Wall Street to Hong Kong to orchestrate a complex web of financing and hedging trades to keep the products running.

So great is this constant drumbeat of buying on up days and selling on down days that investors say the ETF has begun to move the stock rather than simply track it.


A ceremony in Seoul celebrating the KOSPI index breaking 9,000 points on June 18. Photographer: Jung Yeon-Je/AFP/Getty Images


It’s a phenomenon popping up more and more across the globe as a rush by investors to turbocharge bets on the AI boom turns leveraged ETFs into a $270 billion business. And as this new financial alchemy ripples through markets, nowhere are the stakes higher than in Seoul, where SK Hynix accounts for 28% of the Kospi index (and rival Samsung another 29%) and increasingly serves as a global barometer to measure AI bubble angst.

In other words, selloffs in the CSOP SK Hynix ETF, if sustained long enough, could unleash even more pain. Thursday delivered another reminder of that risk: The ETF plunged more than 20%, just as it had done early last week, helping drag the stock down over 10% and triggering a 2% slump in MSCI’s benchmark emerging-market index.

Hong Kong's Leveraged SK Hynix ETF Dwarfs All Rivals
Source: Bloomberg

“I’m not saying that SK Hynix is going to bring down the S&P, but it’s part of a broader pattern,” says Dean Curnutt, chief executive officer of Macro Risk Advisors. “Tech high flyers are delivering such strong returns and there’s sort of a feedback mechanism on the way up that ultimately can play out on the way down as well.”

Declines in SK Hynix and the Kospi, Curnutt says, could trigger “an onslaught of very fast selling.”

At roughly $13 billion in assets, the CSOP ETF is now worth about twice the value of SK Hynix shares that typically change hands in an entire trading day — the most extreme ratio among large stocks with leveraged ETFs tracking them.

That has changed how professionals trade the stock.

Korea's Tech Stars Stand Out for Outsized ETFs Compared to Daily Stock Traded
Source: Bloomberg
Note: Data as of June 29, 2026;
Average daily turnover as of this year and calculation for SK Hynix and Samsung only includes trading on the Korea Stock Exchange

Every afternoon around 1:30 p.m., Ian settles into his desk in Hong Kong preparing to trade SK Hynix shares before the leveraged funds begin their rebalance. The idea is straightforward: get ahead of the predictable buying and selling generated by the ETF, then unwind the position before the market closes.

“It’s easy money,” said Ian, a trader at a market‑making firm who asked not to be identified discussing proprietary strategies. The trick, he added, is timing. Too early risks getting caught by unexpected headlines. Too late means joining a crowded trade.

Ian’s routine illustrates how trading in SK Hynix has evolved. On many desks, estimating the ETF’s end-of-day rebalance has become nearly as important as analyzing the company’s earnings outlook.

The trade works because he knows what comes next. Each afternoon, a sprawling network of banks, hedge funds and market makers begins preparing for the fund’s rebalance. Banks provide swaps that manufacture the leverage promised by the ETF. To hedge those exposures, they buy downside protection from hedge funds and asset managers through exotic derivatives known as cliquets, while also managing positions in SK Hynix shares, futures and options.

In total, CSOP Asset Management Ltd. lists more than 20 counterparties involved in supporting the ETF, including Goldman Sachs Group Inc., Morgan Stanley and other major Wall Street firms. The result is a complex chain of interconnected trades that has become increasingly important to the shares of a company that controls nearly two-thirds of the global high-bandwidth memory chip market.

How CSOP SK Hynix Leveraged ETF Works
Sources: CSOP website, Bloomberg
Note: Data as of June 29, 2026

The pressure is beginning to show inside that machinery.

Banks providing the swaps behind the ETF are running into funding constraints as the product grows. Some are now scaling back the amount of exposure they’re willing to offer on SK Hynix and charging clients more for it, while others have encouraged asset managers to hold the shares directly and enter into swap arrangements with the banks instead, according to people familiar with the matter, who asked not to be identified discussing private information.

Managing that risk is getting more expensive too. The annualized cost of cliquets — derivatives banks buy to protect against a sharp collapse in SK Hynix shares — has risen from about 3% in March to more than 10%, according to pricing seen by Bloomberg.

CSOP has also repeatedly warned investors that new ETF creations could be suspended if counterparties reach risk limits.

None of that suggests the system is failing. But it does show that supporting the world’s largest single-stock leveraged ETF is becoming progressively more expensive.

“For banks’ balance sheets, this is all kind of coming at a bad time,” said Jamie Sandells, portfolio manager at Janus Henderson. “We’ve got record high equity markets, big IPOs and then the leveraged ETF story is on top of that.”


Read more on Korean leveraged ETFs:

The rising cost of maintaining the structure is beginning to show up in performance as well.

Through June 29, the ETF had returned 718% this year, versus roughly 921% for a theoretical portfolio providing perfectly compounded two-times daily exposure, according to Bloomberg Intelligence estimates. Although leveraged ETFs are only intended to deliver twice a stock’s return over a single trading day, the widening gap still reflects the growing costs of sourcing and hedging the exposure needed to keep the strategy running.


Ding Chen during a listing ceremony at the Hong Kong Stock Exchange in 2022. Photographer: Paul Yeung/Bloomberg


CSOP Chief Executive Officer Ding Chen acknowledged this week in an interview that the trade had become “very, very crowded” but said the firm had strengthened risk controls as the fund expanded and closely guarded information about its daily rebalancing activity.

Still, some investors have grown wary. “We are cautious as the trade became really crowded, and technical indicators were flashing red across the board,” said Hao Hong, chief investment officer at Lotus Asset Management Ltd., adding that he’s just sold all the CSOP ETF positions he’s been holding since January.

“Hynix has been making new highs but its relative strength is actually waning. Typically, when this price pattern develops, the stock is due for a correction or consolidation,” he said.

Big Take Asia: Risky Bets Loom Over Asia’s AI Mania (Podcast)
Thanks to the AI boom, stock markets in Taiwan and South Korea have seen historic rallies this year. But as retail investors pile in, often using borrowed money, concerns are growing over whether this momentum is sustainable. On today’s Big Take Asia podcast, guest host Rebecca Choong Wilkins speaks with Bloomberg’s Asian markets reporter Charlotte Yang and Bloomberg Opinion’s Shuli Ren about the risks of betting on AI and how potential fallout could ripple beyond the region.

To be sure, analysts say SK Hynix’s plan for a $29 billion US listing could potentially boost liquidity in its shares and dampen the impact of leveraged ETF flows.

The ETF’s extraordinary growth reflects a combination of timing and access.

It launched just as SK Hynix emerged as one of the biggest winners of the AI boom and was the first leveraged ETF anywhere in the world tied to the stock. As Nvidia Corp.’s leading supplier of HBM chips, SK Hynix became one of the market’s strongest momentum trades.

SK Hynix Shares Soar More Than 800% in the Past Year
Source: Bloomberg
Note: Change since June 30, 2025

For many investors outside Korea, particularly in Hong Kong, the CSOP product also offered one of the simplest ways to make a leveraged single-stock bet on the company. Strong performance attracted more inflows, which in turn required larger rebalancing trades — a cycle that few expected to reach its current scale.

Now, competitors are rushing in. Korea approved 16 copycat leveraged ETFs in May, while similar products are beginning to emerge in the US just as leveraged ETFs more broadly continue to expand.

That proliferation is one reason traders far beyond Seoul are paying attention. To many investors, SK Hynix has become less an isolated anomaly than the market’s most extreme example of how concentrated leveraged products can affect the securities they track.

Nomura strategists estimate leveraged ETFs now generate about $9 billion of rebalancing demand for every 1% move in the market. Barclays Plc estimates rebalancing by US leveraged ETFs has recently climbed to several times its long-term average, creating buying and selling flows potentially large enough to influence broader market trading.

SK Hynix Volatility Surges With Stock Since ETF Debut
Source: Bloomberg

For now, the feedback loop has largely been a virtuous one, outside a few rare exceptions like the sudden plunges at the start of the Iran war and then again last week. As SK Hynix has surged on AI optimism, fresh inflows poured into the ETF, generating profits for banks, hedge funds, market makers and retail traders alike.

The bigger question is what happens if that momentum reverses.

A prolonged tumble would force the ETF to sell into falling markets just as mechanically as it has bought into rising ones, potentially amplifying moves in one of Asia’s most important stocks. Given SK Hynix’s outsized weight in the Kospi, that pressure could quickly spill into index futures and other derivatives tied to the Korean market, now the seventh largest in the world.

The leveraged ETF markets has seen versions of this before. In 2024, some funds tied to Strategy Inc., formerly MicroStrategy, ran into financing constraints at prime brokers after the stock’s extraordinary rally, before suffering outsized losses as Bitcoin retreated.

Korea’s watchdog has already expressed regret over approving copycat leveraged ETFs tied to its biggest chipmakers, saying the products have added to market volatility. More than 90% of investors in those funds are retail traders.

So far, the enthusiasm has shown little sign of fading.


Ron Ding in Hong Kong. Photographer: Paul Yeung/Bloomberg


Ron Ding, a 26-year-old employee at a Hong Kong asset manager, invested HK$1 million ($127,604) of his own savings in the CSOP ETF in late April after becoming convinced SK Hynix would remain the dominant supplier of HBM chips for Nvidia.

“I already have a car,” he said. “I can now afford a Patek Philippe Nautilus.”"""

    device = "cuda" if torch.cuda.is_available() else "cpu"
    dtype = torch.bfloat16 if device == "cuda" else torch.float32

    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = NemotronHForCausalLM.from_pretrained(
        MODEL_NAME,
        dtype=dtype,
        trust_remote_code=True,
    ).to(device)
    setup_hooks(model)

    model.train()

    loss = calculate_loss(model, prompt, tokenizer, device, max_tokens=MAX_TRAIN_TOKENS)
    print_max_memory("After forward pass")

    print(f"Dummy training loss: {loss.item():.4f}")
    loss.backward()
    print_max_memory("After backward pass")

    # inputs = tokenizer(prompt, return_tensors="pt").to(device)
    #
    # with torch.inference_mode():
    #     print("Starting inference: " )
    #     output_ids = model.generate(
    #         **inputs,
    #         max_new_tokens=80,
    #         do_sample=False,
    #         pad_token_id=tokenizer.eos_token_id,
    #     )
    #
    # response = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    # print(response)


if __name__ == "__main__":
    main()
